### ISSUE TITLE
pip install python-mpd2

### ISSUE THREAD

**Issue by TheRadio123** [fsahli/music-cards#6]
i have installed the first 2 python evdev 
i am using a raspberry pi zero w, and it wont let me download the python mpd-2 

could not install packages due to an environmental error

then it says i am using pip version 18.1 however version 19.0.3 is available
you should consider upgrading via the 'pip install --upgrade pip' command

once i do that it tells me my python version is deprecated
and keeps on telling me that it cannot install due to an environmental error

**Comment by TheRadio123** [comment]
![Capture](https://user-images.githubusercontent.com/49263580/55846365-0f3dff80-5b0b-11e9-90e2-2059379064ea.PNG)
Not sure what is going on here :P i restarted my pi and seems to me like it downloaded the last part

**Comment by TheRadio123** [comment]
just need help on the next step. I am a noob.

**Comment by fsahli** [comment]
you probably need to change directory: "cd music-cards" should do the trick

**Comment by TheRadio123** [comment]
not sure what im doing wrong but i cloned the github and loaded onto my SD. When i try to run 'python config.py' it tells me there is no such file or directory
